### ISSUE TITLE
Add story form should clear

### ISSUE THREAD

**Issue by leea10** [leea10/intrigue#36]
Currently, so long as the page doesn't reload, the add story form never clears on its fields on its own. The desired behavior is currently undetermined, but at the very least, the form should clear when a story has been created successfully.

**Comment by leea10** [comment]
This is currently in place for the "Add Character" form. Applying this to the add story form should be extremely simple and done before stakeholder I.

**Comment by MKEspinoza** [comment]
Resolved :D

**Comment by leea10** [comment]
One small code cleanup for extensibility purposes: have the ng-model fields be story.title and story.description and then when clearing the form, $scope.story = null. This way we don't have to clear each field manually. Similar implementation exists in ToolbarController and editor.ejs
