### ISSUE TITLE
Characters in library should be displayed as icons with name underneath

### ISSUE THREAD

**Issue by leea10** [leea10/intrigue#39]
Currently they are temporary form fields

**Comment by leea10** [comment]
Still needs polish, but for the most part, there.

**Comment by leea10** [comment]
For stakeholder I, I think we should at least get the images to crop to the same height on display before resolving this issue.

**Comment by ebi888** [comment]
assets resized

**Comment by leea10** [comment]
Marina centered the name underneath the character icon. I'm gonna call this done for stakeholder one and open another issue for making the images crop to squares.
